#!/bin/bash

FILES="rpi01 rpi02 rpi03 rpi04 rpi05 rpi06 rpi07 rpi08 rpi09 rpi10 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpi18 rpi19 rpi20"


for file in $FILES ; do

   ping -c 1 "$file" &> /dev/null


     if [ $? -eq 0 ] ; then


	echo "$file is alive";

     else

	echo "$file is not alive";

     fi

done
exit 0
